### ISSUE TITLE
No module named 'datasets'

### ISSUE THREAD

**Issue by barneyhill** [archinetai/audio-data-pytorch#1]
Python 3.9.12

```
>>> from audio_data_pytorch import YoutubeDataset
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/home01/mm19bh2/.conda/envs/ad/lib/python3.9/site-packages/audio_data_pytorch/__init__.py", line 1, in <module>
    from .datasets import *  # noqa
  File "/home/home01/mm19bh2/.conda/envs/ad/lib/python3.9/site-packages/audio_data_pytorch/datasets/__init__.py", line 1, in <module>
    from .common_voice_dataset import CommonVoiceDataset
  File "/home/home01/mm19bh2/.conda/envs/ad/lib/python3.9/site-packages/audio_data_pytorch/datasets/common_voice_dataset.py", line 5, in <module>
    from datasets import interleave_datasets, load_dataset
ModuleNotFoundError: No module named 'datasets'
```

Just installed this library using "pip install audio-data-pytorch" and getting this error, any ideas?

Many thanks, 
Barney

**Comment by flavioschneider** [comment]
Ah! Should be fixed in `v0.0.6`.

**Comment by barneyhill** [comment]
Wonderful thank you very much - excellent standard of code btw 👍

**Comment by flavioschneider** [comment]
Thank you! :)
